# vision
VISION_FOCUS_MOVE = 'vfm'
VISION_FOCUS_ZOOM = 'vfz'
ZOOM_TYPE = 'zmt'
DEGREES = 'dgr'
SPEED = 'spd'
DURATION = 'drt'
ACTUAL_SPEED_TIMES = 50
ACTUAL_DEGREES_TIMES = 10
# status
BUSY = 'busy'
SHORT_DURATION = 'S'
MEDIUM_DURATION = 'M'
LONG_DURATION = 'L'

# memory
ID = 'id'
STRENGTH = 'str'
RECALL = 'rcl'
REWARD = 'rwd'
LAST_RECALL = 'lrc'
KERNEL = 'knl'
FEATURE = 'ftr'
SIMILAR = 'sml'
CHANNEL = 'cnl'
PARENT_MEM = 'pmy'
PHYSICAL_MEMORY_TYPE = 'ftt'
SOUND_FEATURE = 'sft'
VISION_FEATURE = 'vft'
SLICE_MEMORY = '4slm'
STATUS = 'sts'
NEW = '7new'
MATCHING = '6mcg'
MATCHED = '5mcd'
EXPIRED = '4xpd'
START_TIME = 'stt'
END_TIME = 'edt'
MEMORY_DURATION = 'mmd'
HAPPEN_TIME = 'hpt'

